# Generated by Django 3.1.7 on 2021-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_element_id', models.CharField(max_length=200)),
                ('activity_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='AddDesignElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'design_elements',
            },
        ),
        migrations.CreateModel(
            name='AddNewHazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_name', models.CharField(max_length=200)),
                ('hazard_permalink', models.CharField(max_length=200)),
                ('activity_id', models.CharField(max_length=200)),
                ('probility', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=200)),
                ('risk', models.CharField(max_length=200)),
                ('control_measure', models.CharField(max_length=500)),
                ('user_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hazards',
            },
        ),
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=200, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=200, null=True)),
                ('date_from', models.CharField(blank=True, max_length=200, null=True)),
                ('date_to', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_by', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='AddSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('EMAIL', models.CharField(max_length=400)),
                ('PASSWORD', models.CharField(blank=True, max_length=200, null=True)),
                ('EXPERIENCE', models.CharField(blank=True, max_length=200, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'modifiers',
            },
        ),
    ]
